version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ["node", "ace", "serve", "--watch"]   # hot reload
    volumes:
      - ./backend:/app         # mount lokálneho kódu
      - /app/node_modules      # node_modules nech ostane v kontajneri
    ports:
      - "3333:3333"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend



volumes:
  pgdata:
